DROP DATABASE IF EXISTS Products;

CREATE DATABASE Products;

USE Products;

CREATE TABLE Products.info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT,
    miniDescription TEXT,
    price DECIMAL (8,2),
    dealLen TEXT,
    regPrice TEXT,
    reviewAvg FLOAT,
    reviewCount INT,
    benefit TEXT NULL,
    size TEXT NULL,
    color TEXT NULL,
    mattress TEXT NULL,
    legs TEXT NULL,
    slattedBedBase TEXT NULL,
    ikeaFamilySale BOOLEAN,
    onSale BOOLEAN,
    new BOOLEAN,
    notQuitePerfect BOOLEAN,
    avaliableForDelivery BOOLEAN,
    assembly BOOLEAN,
    soldSeparate TEXT NULL
);




INSERT INTO Products.info VALUES (
                                  id,
                                  'ANTILOP',
                                  'High chair with tray, white silver color, silver color',
                                  19.99,
                                  null,
                                  null,
                                  4.2,
                                  24,
                                  'ANTILOP high chair is easy to take apart and bring along so your child sits safely whether you are at home, at your friend’s place or at a restaurant. Enjoy your meal!',
                                  null,
                                  null,
                                  null,
                                  null,
                                  null,
                                  false,
                                  false,
                                  false,
                                  false,
                                  true,
                                  true,
                                  null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'TOBIAS',
                                     'Chair, clear, chrome plated',
                                     79.00,
                                     null,
                                     null,
                                     4.3,
                                     73,
                                     'A transparent chair that mirrors its surroundings. It picks up the colors of the room and appears to be floating. And because there’s flexibility in the seat, you may feel like you are floating too.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'HAVSTEN',
                                     'Chair, in/outdoor, beige, 32 5/8x37x35 3/8 "',
                                     260.00,
                                     null,
                                     null,
                                     5.0,
                                     1,
                                     'If you like the look, try how it feels. Generous seats, fluffy cushions as well as elastic mesh fabric make the sofa comfortable. Create your own combination, sit back and relax. Outdoors or indoors!',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'GLENN',
                                     'Bar stool, white, chrome plated, 26 "',
                                     79.99,
                                     null,
                                     null,
                                     4.5,
                                     35,
                                     null,
                                     '26 ", 30 3-8 "',
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'FRANKLIN',
                                     'Bar stool with backrest, foldable, white, white, 24 3/4 "',
                                     29.99,
                                     null,
                                     null,
                                     4.9,
                                     12,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'JULES',
                                     'Child\'s desk chair, white',
                                     34.99,
                                     null,
                                     null,
                                     3.3,
                                     7,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'ÖRFJÄLL',
                                     'Swivel chair, white, Vissle blue',
                                     49.99,
                                     null,
                                     null,
                                     0,
                                     0,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'GRÖNADAL',
                                     'Rocking chair, gray, natural',
                                     249.00,
                                     null,
                                     null,
                                     4.4,
                                     7,
                                     'Hand-woven from rattan and ash makes each and every GRÖNADAL rocking chair one of a kind. The light shape and natural materials bring modern Scandinavian design to mind. Easy to place and yours to love.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'VÅGSBERG / SPORREN',
                                     'Swivel chair, black',
                                     49.99,
                                     null,
                                     null,
                                     2.0,
                                     5,
                                     null,
                                     null,
                                     'Black, Black/white',
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'DIETMAR',
                                     'Underframe for armchair, chrome plated',
                                     40.00,
                                     null,
                                     null,
                                     5.0,
                                     3,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'LANGUR',
                                     'High chair tray, white',
                                     10.00,
                                     null,
                                     null,
                                     0,
                                     0,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'JOKKMOKK',
                                     'Table and 4 chairs, antique stain',
                                     129.00,
                                     null,
                                     null,
                                     4.6,
                                     143,
                                     'A simple and sturdy set that’s perfect for your breakfast nook or smaller dining area. The solid pine holds up well over time and will endure all the family meals and activities around the table.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'STEFAN',
                                     'Chair, brown-black',
                                     25.00,
                                     null,
                                     null,
                                     4.3,
                                     59,
                                     'A sturdy chair with a solid wood construction that can handle the challenges of everyday life! Combines nicely with most styles, and if you’re looking for extra comfort, simply add a chair pad.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'BALTSAR',
                                     'Chair, black-blue, brown',
                                     169.00,
                                     null,
                                     null,
                                     5.0,
                                     1,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'HARRY',
                                     'Chair, black, Knisa light gray',
                                     55.00,
                                     null,
                                     null,
                                     0,
                                     0,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     true,
                                     true,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'MARIUS',
                                     'Stool, black',
                                     5.99,
                                     null,
                                     null,
                                     4.5,
                                     71,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     true,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'MARTIN',
                                     'Chair, black, black',
                                     19.00,
                                     null,
                                     null,
                                     3.7,
                                     3,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'TROLLBERGET',
                                     'Sit/stand support, Glose black',
                                     149.00,
                                     null,
                                     null,
                                     4.6,
                                     5,
                                     'Moves you when seated. This sit/stand support helps you to sit actively. A smart mechanism keeps your body in constant motion, strengthens muscles and the spine – and gives you a naturally healthy posture.',
                                     null,
                                     'Glose black, Grann beige',
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'KOLON',
                                     'Floor protector, 47 1/4x39 3/8 "',
                                     24.99,
                                     null,
                                     null,
                                     3.8,
                                     107,
                                     'A practical solution under your child’s chair at the dining table or under your work chair to spare your floor from spills, wear and dirt. It’s transparent so your rug or floor will shine through.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'MALINDA',
                                     'Chair pad, light beige, 16/14x15x3 "',
                                     4.49,
                                     null,
                                     null,
                                     4.3,
                                     48,
                                     'The extra thick filling provides soft, cushiony comfort even on the hardest of chairs. Two identical sides offers a longer life – simply turn the chair pad over when one side becomes worn or dirty.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     false,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'GONATT',
                                     'Crib, light gray, 27 1/2x52 "',
                                     199.00,
                                     null,
                                     null,
                                     3.6,
                                     15,
                                     'You can both see and feel that every detail of this crib is made with care. Soft shapes, durable materials and a steady construction with practical features and spacious drawers at the bottom.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'NORDLI',
                                     'Bed with headboard and storage, white, King',
                                     649.00,
                                     null,
                                     null,
                                     4.2,
                                     19,
                                     null,
                                     'King, Queen',
                                     'Anthracite, White',
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'SAGSTUA',
                                     'Bed frame, black, Full',
                                     149.00,
                                     null,
                                     null,
                                     4.5,
                                     2,
                                     'A classic bed frame with a brass twist. The curved headboard and brass-colored details soften the sturdy steel. Dressed with your favorite linens, it becomes a statement piece and your own personal haven.',
                                     'Full, King, Queen',
                                     'Black, White',
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Slatted bed base and mattress sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'GODFJORD',
                                     'Bed frame, gray, Queen',
                                     419.00,
                                     null,
                                     null,
                                     4.3,
                                     4,
                                     null,
                                     'King, Queen',
                                     null,
                                     null,
                                     null,
                                     '-, Leirsund, Lönset, Luröy',
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'SONGESAND',
                                     'Bed frame with 4 storage boxes, brown, Full/Double',
                                     249.00,
                                     null,
                                     null,
                                     3.4,
                                     8,
                                     'A sturdy bed frame with soft, profile edges and high legs. A classic shape that will last for many years. Also, there are spacious storage boxes under the bed where you can store bedding or clothes.',
                                     'Full/double, Queen',
                                     'Brown, White',
                                     null,
                                     null,
                                     '-, Lönset, Luröy',
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'DELAKTIG',
                                     'Bed frame/headboard/2 side tables, aluminum, rattan, Queen',
                                     559.00,
                                     null,
                                     null,
                                     0,
                                     0,
                                     'With this bed frame you always have books and glasses close at hand. It’s also easier when cleaning since the bedside tables are attached to the frame.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'HEMNES',
                                     'Bed frame with 4 storage boxes, dark gray stained, Leirsund, Queen',
                                     559.00,
                                     null,
                                     null,
                                     4.0,
                                     6,
                                     null,
                                     'Full, King, Queen',
                                     'Black-brown, Dark gray stained, White stain',
                                     null,
                                     null,
                                     '-, Leirsund, Lönset, Luröy',
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'ESPEVÄR',
                                     'Divan bed, Mausund medium firm, natural, Queen',
                                     1129.00,
                                     null,
                                     null,
                                     4.0,
                                     1,
                                     null,
                                     'Full, King, Queen',
                                     null,
                                     'Hidrasund firm/tistedal natural, Mausund medium firm/natural',
                                     'Båtsfjord, Burfjord',
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'UTÅKER',
                                     'Stackable bed with 2 mattresses, pine, Husvika, Twin',
                                     359.00,
                                     '(Nov 27, 2019 - Dec 8, 2019 while supplies last in participating US stores)',
                                     'Regular price $389.00/2 pack',
                                     4.8,
                                     13,
                                     'When stacked, these 2 beds become a single bed or sofa. Unstacked, you get a double bed, corner sofa or spare bed for sleepovers. And, if you need space for yoga, just stack them again.',
                                     null,
                                     null,
                                     'Pine/husvika, Pine/meistervik, Pine/minnesund',
                                     null,
                                     null,
                                     true,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Bed linen sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'KVALFJORD',
                                     'Bed frame, Risane natural, Luröy, Queen',
                                     649.00,
                                     null,
                                     null,
                                     5.0,
                                     2,
                                     null,
                                     'King, Queen',
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Mattress is sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'NEIDEN',
                                     'Bed frame, pine birch, Luröy, Full',
                                     99.00,
                                     null,
                                     null,
                                     3.9,
                                     37,
                                     'The natural solid wood is beautiful as it is or you can make it more personal by staining, painting or waxing it. Also, the bed frame is high enough so you can place storage boxes underneath.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'HEMMAHOS',
                                     'Children''s tent, caravan',
                                     34.99,
                                     null,
                                     null,
                                     4.0,
                                     67,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'LÖVA',
                                     'Bed canopy, green',
                                     14.99,
                                     null,
                                     null,
                                     4.4,
                                     14,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'MINNEN',
                                     'Ext bed frame with slatted bed base, white, 38 1/4x74 3/4 "',
                                     99.00,
                                     null,
                                     null,
                                     5.0,
                                     4,
                                     'This extendable bed grows as your child grows – without lightening your wallet. Every detail is made with care and the timeless look is easy to match with other furniture.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'SLÄKT',
                                     'Bed frame w/storage+slatted bedbase, white, Twin',
                                     279.00,
                                     null,
                                     null,
                                     3.7,
                                     7,
                                     'A teenager''s dream. A nice bed with lots of storage that swallows up everything. Allowing you to store all of your teen''s stuff in a small space and at a comfortable distance.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'VITVAL',
                                     'Loft bed frame with desk top, white, light gray, Twin',
                                     229.00,
                                     null,
                                     null,
                                     5.0,
                                     3,
                                     'It is the details that make this loft bed unique. Soft shapes, fabric guardrails and a desk with a practical pegboard. You can also accessorize with products from the MÖJLIGHET and SKÅDIS series.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     true,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'TUFFING',
                                     'Bunk bed frame, dark gray, Twin',
                                     119.00,
                                     null,
                                     null,
                                     3.9,
                                     176,
                                     'It has passed the same strict safety tests as all our other bunk beds. To bring the price down we just used other materials and made the bed lower. It came out pretty cool!',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     true,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'NORDDAL',
                                     'Bunk bed frame, black-brown, Twin',
                                     299.00,
                                     null,
                                     null,
                                     4.4,
                                     26,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'MYDAL',
                                     'Bunk bed frame, pine, Twin',
                                     179.00,
                                     null,
                                     null,
                                     4.7,
                                     41,
                                     'This bunk bed is made of untreated solid wood – a durable material that lasts for generations. Can be painted in a favorite color and recycled. Good for your wallet and the environment.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Mattress and bedlinens are sold separately.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'ALLEMANSRÄTTEN',
                                     'Vegetable balls, frozen, 100% vegetables vegan',
                                     7.99,
                                     null,
                                     null,
                                     4.3,
                                     6,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     true,
                                     false,
                                     false,
                                     false,
                                     false,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'HAMNSKÄR',
                                     'Bath faucet with strainer, brass brass color',
                                     89.99,
                                     null,
                                     null,
                                     5.0,
                                     2,
                                     'You save hot water and energy every time you lift the lever. The cold start function avoids the unnecessary use of hot water for daily rituals like washing your hands or brushing your teeth.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'LILLSVAN',
                                     'Bath faucet with strainer, chrome plated',
                                     39.99,
                                     null,
                                     null,
                                     2.0,
                                     1,
                                     'You save hot water and energy every time you lift the lever. The cold start function avoids the unnecessary use of hot water for daily rituals like washing your hands or brushing your teeth.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'VOXNAN',
                                     'Faucet, tall, chrome plated',
                                     89.99,
                                     null,
                                     null,
                                     4.0,
                                     1,
                                     'You save hot water and energy every time you lift the lever. The cold start function avoids the unnecessary use of hot water for daily rituals like washing your hands or brushing your teeth.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'RUNSKÄR',
                                     'Bath faucet with strainer, chrome plated',
                                     49.99,
                                     null,
                                     null,
                                     4.4,
                                     14,
                                     'Reduce your water bills and do a good deed for the environment by using our water-saving heroes. All our faucets include a pressure compensating aerator that saves up to 50% of water usage.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'STOCKHOLM',
                                     'Mirror, walnut veneer, 23 5/8 ',
                                     59.99,
                                     null,
                                     null,
                                     5.0,
                                     6,
                                     'The streamlined shape and the walnut veneer give each mirror a unique character. The frame around the bottom of the mirror forms a shelf where you can put your mobile phone or wallet.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     true,
                                     false,
                                     true,
                                     false,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'ISFJORDEN',
                                     'Floor mirror, black-brown stain, 18 1/2x71 5/8 "',
                                     149.00,
                                     null,
                                     null,
                                     4.7,
                                     6,
                                     'Use the smart little shelf underneath for things like a hair dryer or brushes and the knobs on the sides to hang belts and jewelry. A genuine and romantic feeling with a straightforward design in solid wood.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'KAITUM',
                                     'Mirror with built-in light, battery operated, 7 7/8 "',
                                     29.99,
                                     null,
                                     null,
                                     3.7,
                                     95,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     'Batteries are sold separately, 4-AA size 1.5V (LR6) required.'
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'IKORNNES',
                                     'Table mirror, ash, 10 5/8x15 3/4 "',
                                     29.99,
                                     null,
                                     null,
                                     4.4,
                                     10,
                                     'This mirror works just as well on a chest of drawers as on a wall. When it’s on the wall you can use the stand to hang your scarves or ties. The soft shapes and warm ash veneer create a cozy feeling.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'GODMORGON',
                                     'Box with lid, set of 5, smoked, 9 ½x7 ¾x4 "',
                                     14.99,
                                     null,
                                     null,
                                     4.9,
                                     7,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     true,
                                     true,
                                     true,
                                     null
                                 );
INSERT INTO Products.info VALUES (
                                     id,
                                     'SAXBORGA',
                                     'Jar with lid and tray, set of 5, glass cork',
                                     14.99,
                                     null,
                                     null,
                                     4.5,
                                     15,
                                     'With the jars and storage box you can easily keep all those smaller items organized, and to bring them with you when you need them somewhere else.',
                                     null,
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     false,
                                     false,
                                     true,
                                     false,
                                     null
                                 );

